### ISSUE TITLE
panic: SSH tunnel failed:

### ISSUE THREAD

**Issue by lanow72** [andreasf/cf-mysql-plugin#16]
Hello,

my mysql connexion works , but suddenly it doesn't work, 

all mysql connexion of an org don't work , on a other org it's ok
my ssh connexion is ok 

version driver mysql-plugin: 2.0.0

**my error:**
**cf mysql forum-oft-aero-OMFRED-mysql
panic: SSH tunnel failed: Erreur lors de l'ouverture de la connexion SSH : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

goroutine 37 [running]:
github.com/andreasf/cf-mysql-plugin/cfmysql.(*sshRunner).OpenSshTunnel(0xaabd30, 0x88b900, 0xc04210e840, 0xc04200a860, 0x1b, 0xc04211a490, 0xe, 0xc04211a500, 0x4, 0xc0422264e0, ...)
        /home/travis/gopath/src/github.com/andreasf/cf-mysql-plugin/cfmysql/ssh_runner.go:25 +0x267
created by github.com/andreasf/cf-mysql-plugin/cfmysql.(*cfService).OpenSshTunnel
        /home/travis/gopath/src/github.com/andreasf/cf-mysql-plugin/cfmysql/cf_service.go:61 +0x10e**

**Comment by andreasf** [comment]
Hi,

it sounds like SSH is disabled for the spaces of your other org. Did you try manually connecting to the app via `cf ssh`?

If both orgs are part of the same foundation, a user with `SpaceManager` role should be able to enable SSH for the spaces with `cf allow-space-ssh`. It's documented here: https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#enable-disable-ssh

**Comment by lanow72** [comment]
Hi the connexion ssh is ok 

I send  cf allow-space-ssh forum-oft-aero
ok
but cf mysql forum-oft-aero-OMFRED-mysql but always failed
in this error the goroutine X (running) et always different ???:


panic: SSH tunnel failed: Erreur lors de l'ouverture de la connexion SSH : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

**goroutine 26 [running]:**
github.com/andreasf/cf-mysql-plugin/cfmysql.(*sshRunner).OpenSshTunnel(0xaabd30, 0x88b900, 0xc04216e210, 0xc04200a860, 0x1b, 0xc042125f90, 0xe, 0xc0422a0000, 0x4, 0xc04210cf00, ...)
        /home/travis/gopath/src/github.com/andreasf/cf-mysql-plugin/cfmysql/ssh_runner.go:25 +0x267
created by github.com/andreasf/cf-mysql-plugin/cfmysql.(*cfService).OpenSshTunnel
        /home/travis/gopath/src/github.com/andreasf/cf-mysql-plugin/cfmysql/cf_service.go:61 +0x10e

**Comment by lanow72** [comment]
cf disallow-space-ssh forum-oft-aero ok
cf disable-ssh forum-oft-aero-OMFRED ok
cf allow-space-ssh forum-oft-aero ok
cf enable-ssh forum-oft-aero-OMFRED ok
cf ssh forum-oft-aero-OMFRED ok
but 
 cf mysql forum-oft-aero-OMFRED-mysql
panic: SSH tunnel failed: Erreur lors de l'ouverture de la connexion SSH : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

goroutine 53 [running]:
github.com/andreasf/cf-mysql-plugin/cfmysql.(*sshRunner).OpenSshTunnel(0xaabd30, 0x88b900, 0xc04217a220, 0xc04200a860, 0x1b, 0xc04229b460, 0xe, 0xc04229b4c8, 0x4, 0xc04200d7a0, ...)
        /home/travis/gopath/src/github.com/andreasf/cf-mysql-plugin/cfmysql/ssh_runner.go:25 +0x267
created by github.com/andreasf/cf-mysql-plugin/cfmysql.(*cfService).OpenSshTunnel
        /home/travis/gopath/src/github.com/andreasf/cf-mysql-plugin/cfmysql/cf_service.go:61 +0x10e


And it the same probleme with all mysqldatabase of my org
